version: "3"

services:
  bee-1:
    image: ethersphere/bee:stable
    restart: unless-stopped
    environment:
      - BEE_API_ADDR
      - BEE_BLOCK_TIME
      - BEE_BOOTNODE
      - BEE_BOOTNODE_MODE
      - BEE_CONFIG
      - BEE_CORS_ALLOWED_ORIGINS
      - BEE_DATA_DIR
      - BEE_CACHE_CAPACITY
      - BEE_DB_OPEN_FILES_LIMIT
      - BEE_DB_BLOCK_CACHE_CAPACITY
      - BEE_DB_WRITE_BUFFER_SIZE
      - BEE_DB_DISABLE_SEEKS_COMPACTION
      - BEE_FULL_NODE
      - BEE_NAT_ADDR
      - BEE_NETWORK_ID
      - BEE_P2P_ADDR
      - BEE_P2P_QUIC_ENABLE
      - BEE_P2P_WS_ENABLE
      - BEE_PASSWORD
      - BEE_PASSWORD_FILE
      - BEE_PAYMENT_EARLY_PERCENT
      - BEE_PAYMENT_THRESHOLD
      - BEE_PAYMENT_TOLERANCE_PERCENT
      - BEE_POSTAGE_STAMP_ADDRESS
      - BEE_RESOLVER_OPTIONS
      - BEE_SWAP_ENABLE
      - BEE_BLOCKCHAIN_RPC_ENDPOINT
      - BEE_SWAP_FACTORY_ADDRESS
      - BEE_SWAP_LEGACY_FACTORY_ADDRESSES
      - BEE_SWAP_INITIAL_DEPOSIT
      - BEE_SWAP_DEPLOYMENT_GAS_PRICE
      - BEE_TRACING_ENABLE
      - BEE_TRACING_ENDPOINT
      - BEE_TRACING_SERVICE_NAME
      - BEE_TRANSACTION
      - BEE_VERBOSITY
      - BEE_WELCOME_MESSAGE
      - BEE_MAINNET
    ports:
      - "${API_ADDR:-1633}${BEE_API_ADDR:-:1633}"
      - "${P2P_ADDR:-1634}${BEE_P2P_ADDR:-:1634}"
    volumes:
      - bee-1:/home/bee/.bee
    command: start

volumes:
  bee-1:
